// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn3u-sKYuWLx_B3jrmUi5OciLW6m6B1OY',
    appId: '1:812464941132:web:e9ca1465f51e2f1b362ce9',
    messagingSenderId: '812464941132',
    projectId: 'loginauthentication-7ae6c',
    authDomain: 'loginauthentication-7ae6c.firebaseapp.com',
    storageBucket: 'loginauthentication-7ae6c.firebasestorage.app',
    measurementId: 'G-JB87FCZ740',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeDWBaSFBoeijIUCQu-hD6Xo9ZuK36fBc',
    appId: '1:812464941132:android:e4700991fe644696362ce9',
    messagingSenderId: '812464941132',
    projectId: 'loginauthentication-7ae6c',
    storageBucket: 'loginauthentication-7ae6c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGydke3qzwlcASpF6hWbsEUL5d4JwCcP8',
    appId: '1:812464941132:ios:3d7d8ee40651e44b362ce9',
    messagingSenderId: '812464941132',
    projectId: 'loginauthentication-7ae6c',
    storageBucket: 'loginauthentication-7ae6c.firebasestorage.app',
    iosBundleId: 'com.example.shoppingApp',
  );
}
